name: flutter_application_1
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_widget_from_html: ^0.15.2
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Italic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Satoshi-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi-BlackItalic.ttf
          weight: 900
          style: italic
